name: gitviewer
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  auto_route: ^5.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  flash: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_secure_storage: ^6.0.0
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.0.2
  oauth2: ^2.0.0
  webview_flutter: ^3.0.4

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0

flutter:
  uses-material-design: true
