name: gitviewer
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  oauth2: ^2.0.0
  riverpod:
  flutter_secure_storage: ^4.2.0
  dartz: ^0.10.0-nullsafety.1
  dio: ^4.0.0
  flutter_hooks: ^0.16.0
  hooks_riverpod:
  freezed_annotation: ^0.14.1
  webview_flutter: ^2.0.4
  auto_route: ^2.0.1
  material_design_icons_flutter: ^5.0.5955-rc.1
  json_annotation: ^4.0.1
  sembast: ^3.0.2
  path_provider: ^2.0.1
  path: ^1.8.0
  cached_network_image: ^3.0.0
  shimmer: ^2.0.0
  flash: ^1.5.2
  material_floating_search_bar: ^0.3.4
  url_launcher: ^6.0.3
  flutter_riverpod:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.1
  freezed: ^0.14.1+3
  auto_route_generator: ^2.0.1
  json_serializable: ^4.1.1
  lint: ^1.5.3

flutter:
  uses-material-design: true

assets:
  - .env
